#![warn(
    clippy::correctness,
    clippy::suspicious,
    clippy::style,
    clippy::perf,
    clippy::redundant_type_annotations,
    clippy::dbg_macro
)]
use std::{
    collections::HashMap,
    error::Error,
    ffi::OsString,
    fmt,
    fmt::Display,
    fs,
    net::{IpAddr, SocketAddr, ToSocketAddrs},
    path::PathBuf,
    process::Command,
    sync::{Arc, RwLock},
    thread,
    time::{Duration, Instant},
};

use clap::{Args, Parser, Subcommand};
use slog::{Drain, debug, error, info, o, warn};
use time::{OffsetDateTime, format_description::well_known::Rfc3339};

// all network related code is there, and only there
mod config;
mod network;
mod port_forward;
use self::config::PortForwardMetadata;
use self::config::WGConf;
use self::network::{
    PIA_PORT_FORWARD_API_PORT, PIA_SERVER_API_PORT, add_wg_key, bind_port_forward_port,
    get_port_forward_signature, get_public_ip, get_server_list, get_token, ping_servers,
};
use self::port_forward::Signature as PortForwardSignature;

mod servers;
mod token;
use self::token::Token;
mod wg;
use self::wg::WGPrivateKey;
mod check;

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,

    /// Timeout for every request
    #[arg(
        global = true,
        long,
        short = 't',
        value_name = "SECONDS",
        default_value_t = 3
    )]
    timeout: u64,

    #[arg(global = true, long, env = "DEBUG")]
    debug: bool,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Login with user+password and echo a API token
    Token {
        #[arg(long, requires = "password", env = "PIA_USER")]
        username: String,
        #[arg(long, requires = "username", env = "PIA_PASS")]
        password: String,
    },
    /// List available servers
    Servers {
        /// Filter servers in a specific country (ISO Alpha-2 country codes)
        #[arg(long)]
        country: Option<String>,
        /// Filter servers of a specific region
        #[arg(long)]
        region: Option<String>,
        /// Filter servers that support port forwarding
        #[arg(long)]
        port_forward: bool,
        /// Measure latency to servers by pinging them N times
        #[arg(long, value_name = "N", require_equals = true, num_args = 0..=1, default_missing_value = "3")]
        measure: Option<u8>,
        /// Only list the closest N servers
        #[arg(long, value_name = "N", require_equals = true, num_args = 0..=1, default_missing_value = "5")]
        top: Option<u8>,
    },
    /// Generates a new wireguard config
    Create {
        #[command(flatten)]
        auth: AuthOptions,
        /// The name of the region to generate the wg.conf for. Use the servers command to find an
        /// appropriate one for you.
        #[arg(long)]
        region: String,
        /// Use PIA's DNS when active (requires to use wg-quick)
        #[arg(long)]
        dns: bool,
        /// Measure latency to servers by pinging them N times
        #[arg(long, value_name = "N", default_value_t = 3)]
        measure: u8,
        /// Filter servers that support port forwarding
        #[arg(long)]
        port_forward: bool,
    },
    /// Verify the VPN connection is active and used
    Check { conf: PathBuf },
    /// Register and maintain a forwarded port on an active PIA WireGuard tunnel
    Port {
        #[command(subcommand)]
        command: PortCommands,
    },
}

#[derive(Subcommand, Debug)]
enum PortCommands {
    /// Request a forwarded port
    Register {
        #[command(flatten)]
        auth: AuthOptions,
        /// Path to the WireGuard config generated by `create`
        #[arg(long)]
        conf: PathBuf,
    },
    /// Bind a forwarded port and optionally keep it alive
    Activate {
        /// Path to the WireGuard config generated by `create`
        #[arg(long)]
        conf: PathBuf,
        /// Bind once and exit after running the callback
        #[arg(long)]
        once: bool,
        /// Wait N seconds between successful bind renewals
        #[arg(long, default_value_t = 300, value_name = "SECONDS")]
        bind_interval: u64,
        /// Retry a failed bind after N seconds
        #[arg(long, default_value_t = 10, value_name = "SECONDS")]
        bind_failure_interval: u64,
        /// Abort after N consecutive bind failures
        #[arg(long, default_value_t = 5, value_name = "N")]
        bind_max_attempts: u8,
        /// Command to run with the forwarded port exported as PIA_PORT
        #[arg(default_value = "echo")]
        callback: OsString,
    },
}

#[derive(Args, Debug, Clone)]
#[group(required = true)]
struct AuthOptions {
    #[arg(long, conflicts_with = "username", env = "PIA_TOKEN")]
    token: Option<String>,
    #[arg(long, requires = "password", env = "PIA_USER")]
    username: Option<String>,
    #[arg(long, requires = "username", env = "PIA_PASS")]
    password: Option<String>,
}
impl AuthOptions {
    fn get_token(
        &self,
        log: &slog::Logger,
        agent_public: &ureq::Agent,
    ) -> Result<Token, Box<dyn Error>> {
        match &self.token {
            Some(token) => Ok(token.clone()),
            None => Ok(get_token(
                log,
                agent_public,
                &self.username.clone().expect("username has to be set"),
                &self.password.clone().expect("password has to be set"),
            )?),
        }
    }
}

fn make_logger(debug: bool) -> slog::Logger {
    let decorator = slog_term::TermDecorator::new().build();
    let drain = slog_term::CompactFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain)
        .overflow_strategy(slog_async::OverflowStrategy::Block)
        .build()
        .fuse();
    let drain = drain
        .filter_level(if debug {
            slog::Level::Debug
        } else {
            slog::Level::Info
        })
        .fuse();

    slog::Logger::root(drain, o!())
}

#[derive(Clone)]
struct ResolverStore {
    db: Arc<RwLock<HashMap<String, SocketAddr>>>,
    log: slog::Logger,
}
impl fmt::Debug for ResolverStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ResolverStore").finish()
    }
}
impl ResolverStore {
    fn new(log: &slog::Logger) -> Self {
        Self {
            db: Arc::default(),
            log: log.clone(),
        }
    }
    fn add<S>(&self, fqdn: S, port: u16, addr: IpAddr)
    where
        S: Display,
    {
        let name = format!("{fqdn}:{port}");
        let addr = SocketAddr::new(addr, port);
        debug!(self.log, "adding new resolver entry"; "name" => name.clone(), "addr" => addr.to_string());
        self.db
            .write()
            .expect("ResolverStore could not acquire write lock")
            .insert(name, addr);
    }
}
impl ureq::unversioned::resolver::Resolver for ResolverStore {
    fn resolve(
        &self,
        uri: &ureq::http::Uri,
        _config: &ureq::config::Config,
        _timeout: ureq::unversioned::transport::NextTimeout,
    ) -> Result<ureq::unversioned::resolver::ResolvedSocketAddrs, ureq::Error> {
        let authority = uri
            .authority()
            .ok_or_else(|| ureq::Error::BadUri("URI has no authority".into()))?;
        let scheme = uri
            .scheme_str()
            .ok_or_else(|| ureq::Error::BadUri("URI has no scheme".into()))?;
        let port = authority.port_u16().unwrap_or(match scheme {
            "http" => 80,
            "https" => 443,
            _ => {
                return Err(ureq::Error::BadUri(
                    format!("unknown scheme: {scheme}").into(),
                ));
            }
        });
        let netloc = format!("{}:{port}", authority.host());

        let db = self.db.read().expect("ResolverStore RwLock was poisoned");
        let num_entries = db.len();
        let entry = db.get(&netloc).copied();
        drop(db);

        let mut resolved = ureq::unversioned::resolver::ResolvedSocketAddrs::from_fn(|_| {
            SocketAddr::new(IpAddr::from([0, 0, 0, 0]), 0)
        });
        match entry {
            Some(addr) => resolved.push(addr),
            None => {
                for addr in netloc.to_socket_addrs()?.take(16) {
                    resolved.push(addr);
                }
            }
        }

        debug!(self.log, "resolved addr"; "name" => netloc, "addr" => format!("{:?}", resolved), "entries" => num_entries);
        if resolved.is_empty() {
            Err(ureq::Error::HostNotFound)
        } else {
            Ok(resolved)
        }
    }
}

fn make_http_agents(
    log: &slog::Logger,
    timeout: Duration,
) -> (ureq::Agent, ureq::Agent, ResolverStore) {
    let store = ResolverStore::new(log);
    let agent_public = ureq::Agent::config_builder()
        .timeout_global(Some(timeout))
        .tls_config(
            ureq::tls::TlsConfig::builder()
                .provider(ureq::tls::TlsProvider::Rustls)
                .root_certs(ureq::tls::RootCerts::PlatformVerifier)
                .build(),
        )
        .user_agent(format!("{}/{}", env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION")).as_str())
        .build();
    let agent_public = ureq::Agent::with_parts(
        agent_public,
        ureq::unversioned::transport::DefaultConnector::default(),
        store.clone(),
    );

    let pia_ca = ureq::tls::Certificate::from_pem(include_bytes!("../ca.rsa.4096.crt"))
        .expect("Error parsing the embedded PIA CA certificate");
    let agent_pia = ureq::Agent::config_builder()
        .timeout_global(Some(timeout))
        .tls_config(
            ureq::tls::TlsConfig::builder()
                .provider(ureq::tls::TlsProvider::Rustls)
                .root_certs(ureq::tls::RootCerts::new_with_certs(&[pia_ca]))
                .build(),
        )
        .user_agent(format!("{}/{}", env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION")).as_str())
        .build();
    let agent_pia = ureq::Agent::with_parts(
        agent_pia,
        ureq::unversioned::transport::DefaultConnector::default(),
        store.clone(),
    );

    (agent_public, agent_pia, store)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli_args = Cli::parse();
    let timeout = Duration::from_secs(cli_args.timeout);

    let log = make_logger(cli_args.debug);

    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("could not install default crypto provider");
    let (agent_public, agent_pia, resolver_store) = make_http_agents(&log, timeout);

    debug!(log, "startup"; "args" => format!("{:?}", cli_args));

    match cli_args.command {
        Commands::Token { username, password } => {
            println!("{}", get_token(&log, &agent_public, &username, &password)?);
        }
        Commands::Servers {
            country,
            region,
            port_forward,
            measure,
            top,
        } => {
            let mut servers = get_server_list(&log, &agent_public)?;

            if let Some(country) = country {
                servers.retain(|s| s.country.to_lowercase() == country.to_lowercase());
            }

            if let Some(region) = region {
                servers.retain(|s| s.region_id == region || s.region_name == region);
            }

            if port_forward {
                servers.retain(|s| s.port_forward);
            }

            if servers.is_empty() {
                error!(log, "no servers found matching your criteria");
                Err("no servers found matching your criteria")?;
            }

            if let Some(measure) = measure {
                let ping_results = ping_servers(&log, &servers, measure, timeout)?;
                let mut servers = servers.enrich(&ping_results);

                if let Some(top) = top {
                    servers.top(top);
                }

                drop(log); // flush all log messages
                for (median_ping, s) in servers {
                    #[allow(clippy::cast_precision_loss)]
                    let median_ping = median_ping.map_or("unreachable".to_string(), |p| {
                        format!("{:>6.2}ms", p.as_nanos() as f32 / 1_000_000_f32)
                    });
                    println!(
                        "found server: {} {:16} {:16} {:2} {:19} {:34} {:12} dns {}",
                        median_ping,
                        s.name,
                        s.ip.to_string(),
                        s.country,
                        s.region_id,
                        s.region_name,
                        if s.port_forward { "port forward" } else { "" },
                        s.dns_server,
                    );
                }
            } else {
                drop(log); // flush all log messages
                for s in servers {
                    println!(
                        "found server: {:2} {:16} {:16} {:19} {:34} {:12} dns {}",
                        s.name,
                        s.ip.to_string(),
                        s.country,
                        s.region_id,
                        s.region_name,
                        if s.port_forward { "port forward" } else { "" },
                        s.dns_server,
                    );
                }
            }
        }
        Commands::Create {
            auth,
            region,
            measure,
            port_forward,
            dns,
        } => {
            let servers = get_server_list(&log, &agent_public)?;
            let mut servers = servers.get_region(&region);
            if port_forward {
                servers.retain(|s| s.port_forward);
            }
            if servers.is_empty() {
                error!(log, "requested region not found");
                Err("requested region not found")?;
            }

            let ping_results = ping_servers(&log, &servers, measure, timeout)?;
            let mut servers = servers.enrich(&ping_results);
            let server = servers.best().ok_or("No suitable server found")?;

            let token = auth.get_token(&log, &agent_public)?;
            let private_key = WGPrivateKey::new();
            let public_key = private_key.public();

            resolver_store.add(&server.name, PIA_SERVER_API_PORT, server.ip);
            let added = add_wg_key(&log, &agent_pia, &token, &server, &public_key)?;

            let mut conf = WGConf::from(added, private_key);
            if !dns {
                conf.disable_dns();
            }

            let ini = conf.to_ini()?;
            println!("{ini}");
        }
        Commands::Check { conf } => {
            let conf = fs::read_to_string(conf)?;
            let conf = WGConf::from_ini(&conf)?;
            let public = get_public_ip(&log, &agent_public)?;
            println!(
                "IP: {}, country: {}, ISP: {}",
                public.ip, public.country, public.isp
            );
            if public.ip != conf.peer.endpoint.ip() {
                error!(
                    log,
                    "Not connected to PIA. Request went through the open internet"
                );
                return Err("Not connected to PIA. Request went through the open internet".into());
            }
            info!(
                log,
                "IP matches our VPN server, request got routed through VPN"
            );
        }
        Commands::Port { command } => match command {
            PortCommands::Register { auth, conf } => {
                let token = auth.get_token(&log, &agent_public)?;
                let mut wg_conf = WGConf::from_path(&conf)?;
                let (server_name, server_ip) = wg_conf.port_forward_target()?;
                resolver_store.add(&server_name, PIA_PORT_FORWARD_API_PORT, server_ip);
                let signature = get_port_forward_signature(&log, &agent_pia, &token, &server_name)?;
                wg_conf.peer.port_forward_port = Some(signature.payload.port);
                wg_conf.peer.port_forward_expiration =
                    Some(signature.payload.expires_at.format(&Rfc3339)?);
                wg_conf.peer.port_forward_payload = Some(signature.payload_raw);
                wg_conf.peer.port_forward_signature = Some(signature.signature);
                let ini = wg_conf.to_ini()?;

                match fs::write(&conf, &ini) {
                    Ok(()) => {
                        println!(
                            "registered port {} in {}",
                            signature.payload.port,
                            conf.display()
                        );
                    }
                    Err(err) => {
                        warn!(
                            log,
                            "could not write updated config; falling back to stdout";
                            "path" => conf.display().to_string(),
                            "error" => err.to_string()
                        );
                        println!("{ini}");
                    }
                }
            }
            PortCommands::Activate {
                conf,
                once,
                bind_interval,
                bind_failure_interval,
                bind_max_attempts,
                callback,
            } => {
                let mut consecutive_bind_failures = 0u8;

                loop {
                    let conf = WGConf::from_path(&conf)?;
                    let (server_name, server_ip) = conf.port_forward_target()?;
                    resolver_store.add(&server_name, PIA_PORT_FORWARD_API_PORT, server_ip);
                    let signature: PortForwardSignature = conf.port_forward_signature()?;
                    if signature.is_expired(OffsetDateTime::now_utc()) {
                        warn!(
                            log,
                            "stored port-forward registration is expired";
                            "server" => server_name,
                            "ip" => server_ip.to_string(),
                            "expires_at" => signature.payload.expires_at.to_string()
                        );
                    }

                    let next_bind_at = Instant::now() + Duration::from_secs(bind_interval);
                    let bind = bind_port_forward_port(&log, &agent_pia, &server_name, &signature);
                    let Ok(bind) = bind else {
                        let err =
                            bind.expect_err("let-else error branch must contain the bind error");
                        consecutive_bind_failures += 1;
                        warn!(
                            log,
                            "port forward bind failed";
                            "server" => server_name,
                            "ip" => server_ip.to_string(),
                            "attempt" => consecutive_bind_failures,
                            "max_attempts" => bind_max_attempts,
                            "error" => err.to_string()
                        );
                        if consecutive_bind_failures >= bind_max_attempts {
                            return Err(format!(
                                "bindPort failed {consecutive_bind_failures} times in a row: {err}"
                            )
                            .into());
                        }
                        thread::sleep(Duration::from_secs(bind_failure_interval));
                        continue;
                    };
                    consecutive_bind_failures = 0;

                    info!(
                        log,
                        "port forward active";
                        "server" => server_name,
                        "ip" => server_ip.to_string(),
                        "port" => signature.payload.port,
                        "message" => bind.message.as_str(),
                    );

                    let port = signature.payload.port.to_string();
                    let status = Command::new(&callback)
                        .arg(&port)
                        .arg(bind.status.as_str())
                        .arg(bind.message.as_str())
                        .env("PIA_PORT", &port)
                        .env("PIA_PORT_STATUS", bind.status.as_str())
                        .env("PIA_PORT_MESSAGE", bind.message.as_str())
                        .status()?;
                    if !status.success() {
                        return Err(
                            format!("callback exited with non-zero status: {status}").into()
                        );
                    }

                    if once {
                        break;
                    }

                    if let Some(remaining) = next_bind_at.checked_duration_since(Instant::now()) {
                        thread::sleep(remaining);
                    }
                }
            }
        },
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn verify_cli_help_in_readme() {
        let mut cmd = Cli::command();
        let help = cmd.render_help().to_string();
        let expected_help = include_str!("../README.md")
            .split("```")
            .nth(1)
            .unwrap()
            .trim();
        assert_eq!(help.trim(), expected_help);
    }

    #[test]
    fn verify_rust_version_consistency() {
        let cargo_toml = include_str!("../Cargo.toml");
        let readme = include_str!("../README.md");
        let ci_yml = include_str!("../.github/workflows/ci.yml");

        let cargo_version = cargo_toml
            .lines()
            .find(|line| line.starts_with("rust-version"))
            .and_then(|line| line.split('"').nth(1))
            .expect("Rust version not found in Cargo.toml");

        let readme_version = readme
            .lines()
            .find(|line| line.contains("rust-") && line.contains("%2B"))
            .and_then(|line| line.split('-').nth(1))
            .and_then(|v| v.split('%').next())
            .expect("Rust version not found in README.md");

        let ci_version = ci_yml
            .lines()
            .find(|line| line.contains("'1."))
            .and_then(|line| line.split('\'').nth(1))
            .expect("Rust version not found in ci.yml");

        assert_eq!(
            cargo_version, readme_version,
            "Cargo.toml and README.md versions don't match"
        );
        assert_eq!(
            cargo_version, ci_version,
            "Cargo.toml and ci.yml versions don't match"
        );
    }
}
